### ISSUE TITLE
Code doesnt work for me, returns duplicate entries in Top 10

### ISSUE THREAD

**Issue by Meai** [helipilot50/aerospike-top-10-aggregation#1]
No idea why, I just thought I'd make an issue. 

I inserted 15 records only for testing, still 2 duplicates.
I'm fairly bad at lua, so maybe it's a simple lua programming error? idk

**Comment by helipilot50** [comment]
The example finds the top ten values, but does not filter duplicates. Essentially it's a leader board and it works for these kind of use cases:

"Find the top 10 students in a class of 1000" or "find the 10 most recent events". 

If you want to find the top ten distinct things, you will need to modify the insertion sort functionality in the Aggregate function `accumulate()` and the Reduce function `reducer()` to exclude duplicates.

**Comment by Meai** [comment]
I dont see how it makes sense for a leaderboard to have duplicate entries at all. I have 15 distinct values in the database and I want to find the top 10 of those. Obviously I dont want the highest entry 10 times.

**Comment by helipilot50** [comment]
(Smile) It makes sense for the use case "Find the top 10 students in a class of 1000". That is the the kind of use case the example was written for.

If you want to find the top 10 distinct things, you will need to modify the insertion sort functionality in the Aggregate function `accumulate()` and the Reduce function `reducer()` to exclude duplicates.
